#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import concurrent.futures
import os
import sys
from datetime import datetime, date
import time
from typing import List, Optional, Sequence, Tuple
from pathlib import Path

import pandas as pd
import numpy as np
import jqdatasdk
from sqlalchemy import bindparam, text
from tqdm import tqdm

# 对齐旧项目：把 common / factor_docs 加入路径
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from common.config import Config
from common.db import get_db_manager
from common.stock_daily_log import log_stock_daily_banner
from common.universe_service import normalize_universe_code, resolve_universe_for_jq
from common.utils import setup_logger
from factor_docs.factor_docs_parser import load_all_factors, FactorDefinition
from factor_engine.factor_dsl_allowlist import (
    assert_locals_dict_keys_match_allowlist,
    validate_factor_dsl_formula,
)

logger = setup_logger("factor_engine_runner", "logs/factor_engine_runner.log")

# 进程池 worker 侧共享行情面板，避免每个任务重复传输同一份 price_df。
_WORKER_PRICE_DF: Optional[pd.DataFrame] = None


def _init_factor_compute_worker(price_df: pd.DataFrame) -> None:
    """初始化进程池 worker 的只读行情面板。"""
    global _WORKER_PRICE_DF
    _WORKER_PRICE_DF = price_df


def _compute_factor_processed_series_worker(task: Tuple[str, str, str]) -> Tuple[str, str, Optional[pd.Series], Optional[str], float]:
    """
    进程池 worker：执行单因子计算 + 标准化。

    返回：
    - factor_id / factor_name
    - processed_series（成功时）
    - error_message（失败时）
    - elapsed_seconds
    """
    factor_id, factor_name, formula = task

    if _WORKER_PRICE_DF is None:
        return factor_id, factor_name, None, "worker 未初始化行情面板", 0.0

    started = time.time()

    try:
        raw_series = compute_factor_values(formula, _WORKER_PRICE_DF)
        processed_series = winsorize_and_standardize(raw_series)
    except Exception as e:
        return factor_id, factor_name, None, str(e), time.time() - started

    return factor_id, factor_name, processed_series, None, time.time() - started


def _auth_jq_if_configured(cfg: Config, config_file: str) -> None:
    """
    尝试登录聚宽（仅在需要解析非 ALL/CUSTOM 域时会调用）。

    统一配置约定：
    - 仅读取当前 config_file（根配置）内的 [jq]
    """
    jq_user = ""
    jq_password = ""
    try:
        jq_user = (cfg.get("jq", "user", fallback="") or "").strip()
        jq_password = (cfg.get("jq", "password", fallback="") or "").strip()
    except Exception:
        jq_user = ""
        jq_password = ""

    if not jq_user or not jq_password:
        raise RuntimeError(
            f"未找到聚宽账号配置，无法解析分域股票池（config_file={config_file}）。"
        )

    jqdatasdk.auth(jq_user, jq_password)


def _filter_price_df_by_universe(
    cfg: Config,
    config_file: str,
    price_df: pd.DataFrame,
    universe: str,
    end_date: str,
) -> pd.DataFrame:
    """
    按领域筛选行情面板（MultiIndex: trade_date, stock_code）。

    约定：
    - ALL：不筛选（保持现有全市场口径）
    - STOCK：仅保留 A 股代码后缀 .SH/.SZ
    - CUSTOM/HS300/ZZ500/INDEX/CSI/ETF/LOF/FUTURES：通过 common.universe_service 解析

    说明：factor_engine 主入口已改为在 _load_stock_daily 的 SQL 侧按域过滤；本函数保留供测试或
    与内存筛选口径对照，避免与 _load_stock_daily 分支逻辑漂移。
    """
    u = normalize_universe_code(universe)

    if u == "ALL":
        return price_df

    if u == "STOCK":
        stock_codes = price_df.index.get_level_values("stock_code")
        mask = stock_codes.str.endswith(".SH") | stock_codes.str.endswith(".SZ")
        return price_df[mask]

    if u in ("CUSTOM", "HS300", "ZZ500", "INDEX", "CSI", "ETF", "LOF", "FUTURES"):
        _auth_jq_if_configured(cfg, config_file=config_file)
        internal_codes, _, _, _ = resolve_universe_for_jq(
            cfg=cfg,
            end_date=end_date,
            section="factor_engine",
            universe_hint=u,
        )
        code_set = set(internal_codes)
        if not code_set:
            return price_df.iloc[0:0]

        mask = price_df.index.get_level_values("stock_code").isin(code_set)
        return price_df[mask]

    raise ValueError(f"不支持的 factor_engine.universe={u}")


def _upsert_factor_value_file(
    session,
    *,
    factor_id: str,
    factor_name: str,
    universe: str,
    rel_path: str,
    date_start: str,
    date_end: str,
    batch_id: str,
    stage: str,
    is_rebase: bool,
) -> None:
    """
    写入/更新 factor_value_files（artifact_type=batch_csv）。

    说明：
    - 唯一键：factor_id + universe + artifact_type + date_start + date_end
    - 路径统一存相对仓库根 POSIX 路径
    """
    # 统一转 date，避免 SQL 里做类型强转导致方言差异问题。
    ds = date.fromisoformat(date_start)
    de = date.fromisoformat(date_end)

    params = {
        "factor_id": factor_id,
        "universe": universe,
        "rel_path": rel_path,
        "date_start": ds,
        "date_end": de,
        "batch_id": batch_id,
        "stage": stage,
        "is_rebase": is_rebase,
        "comment": (
            "generated by factor_engine_runner "
            f"universe={universe} batch_id={batch_id} stage={stage} is_rebase={is_rebase}"
        ),
    }

    # 先更新已存在记录。这样不依赖 ON CONFLICT 推断部分唯一索引（WHERE artifact_type='batch_csv'）。
    # 每次 upsert 用 SAVEPOINT 隔离失败，避免一个因子写库失败导致整个 session 进入 aborted。
    # 并且把 factor_basic 的最小 upsert 放在同一个 SAVEPOINT 内，确保外键检查在同一事务视图内可见。
    with session.begin_nested():
        # 先保证 factor_basic 存在，否则插 factor_value_files 会被外键拒绝并导致事务进入 aborted。
        # 这里做最小 upsert：只写必填字段 factor_id / factor_name，其余字段后续可由 pipeline 补齐。
        session.execute(
            text(
                """
                INSERT INTO factor_basic (
                    factor_id,
                    factor_name
                ) VALUES (
                    :factor_id,
                    :factor_name
                )
                ON CONFLICT (factor_id) DO NOTHING
                """
            ),
            {
                "factor_id": factor_id,
                "factor_name": factor_name,
            },
        )

        updated = session.execute(
            text(
                """
                UPDATE factor_value_files
                SET
                    rel_path = :rel_path,
                    batch_id = :batch_id,
                    stage = :stage,
                    is_rebase = :is_rebase,
                    created_at = CURRENT_TIMESTAMP,
                    comment = :comment
                WHERE factor_id = :factor_id
                  AND universe = :universe
                  AND artifact_type = 'batch_csv'
                  AND date_start = :date_start
                  AND date_end = :date_end
                """
            ),
            params,
        )
        if updated.rowcount and updated.rowcount > 0:
            return

        # 未命中更新时再插入新行。
        session.execute(
            text(
                """
                INSERT INTO factor_value_files (
                    factor_id,
                    universe,
                    artifact_type,
                    rel_path,
                    date_start,
                    date_end,
                    trade_date,
                    batch_id,
                    stage,
                    is_rebase,
                    created_at,
                    comment
                ) VALUES (
                    :factor_id,
                    :universe,
                    'batch_csv',
                    :rel_path,
                    :date_start,
                    :date_end,
                    NULL,
                    :batch_id,
                    :stage,
                    :is_rebase,
                    CURRENT_TIMESTAMP,
                    :comment
                )
                """
            ),
            params,
        )


def _factor_value_files_batch_csv_ids_for_job_key(
    session,
    *,
    factor_id: str,
    universe: str,
    date_start: date,
    date_end: date,
) -> List[int]:
    """
    按 batch_csv 写入键查询 factor_value_files 行 id。

    - 应与 _upsert_factor_value_file / 落库的 date_start、date_end 一致。
    - UNIQUE 索引下常为 0/1 行；若为多行则说明数据异常。
    """
    rows = session.execute(
        text(
            """
            SELECT id
            FROM factor_value_files
            WHERE factor_id = :factor_id
              AND universe = :universe
              AND artifact_type = 'batch_csv'
              AND date_start = :date_start
              AND date_end = :date_end
            ORDER BY id ASC
            """
        ),
        {
            "factor_id": factor_id,
            "universe": universe,
            "date_start": date_start,
            "date_end": date_end,
        },
    ).fetchall()
    return [int(r[0]) for r in rows]


def _factor_value_files_daily_csv_ids_for_trade_date(
    session,
    *,
    factor_id: str,
    universe: str,
    trade_date: date,
) -> List[int]:
    """按 daily_csv + trade_date 查询 factor_value_files 行 id（与 daily_factor_values_runner 自然键对齐）。"""
    rows = session.execute(
        text(
            """
            SELECT id
            FROM factor_value_files
            WHERE factor_id = :factor_id
              AND universe = :universe
              AND artifact_type = 'daily_csv'
              AND trade_date = :trade_date
            ORDER BY id ASC
            """
        ),
        {
            "factor_id": factor_id,
            "universe": universe,
            "trade_date": trade_date,
        },
    ).fetchall()
    return [int(r[0]) for r in rows]


def _upsert_factor_value_files_daily_csv(
    session,
    *,
    factor_id: str,
    universe: str,
    rel_path_posix: str,
    trade_date: str,
) -> None:
    """
    真分域日更登记：写 factor_value_files（daily_csv）。
    与 daily_factor_values_runner._upsert_factor_value_files_daily SQL 对齐，避免两处语义分叉。
    """
    td = trade_date.strip()[:10]

    updated = session.execute(
        text(
            """
            UPDATE factor_value_files
            SET rel_path = :rel_path,
                trade_date = :trade_date_td,
                date_start = NULL,
                date_end = NULL,
                created_at = CURRENT_TIMESTAMP
            WHERE factor_id = :factor_id
              AND universe = :universe
              AND artifact_type = 'daily_csv'
              AND trade_date = :trade_date_td
            """
        ),
        {
            "factor_id": factor_id,
            "universe": universe,
            "rel_path": rel_path_posix,
            "trade_date_td": td,
        },
    )

    if int(getattr(updated, "rowcount", 0) or 0) > 0:
        return

    session.execute(
        text(
            """
            INSERT INTO factor_value_files (
                factor_id,
                universe,
                artifact_type,
                rel_path,
                trade_date,
                created_at
            )
            VALUES (
                :factor_id,
                :universe,
                'daily_csv',
                :rel_path,
                :trade_date_td,
                CURRENT_TIMESTAMP
            )
            """
        ),
        {
            "factor_id": factor_id,
            "universe": universe,
            "rel_path": rel_path_posix,
            "trade_date_td": td,
        },
    )


def _load_stock_daily(
    config_file: str,
    start_date: str,
    end_date: str,
    *,
    cfg: Optional[Config] = None,
    universe: Optional[str] = None,
) -> pd.DataFrame:
    """从 stock_daily 拉取行情数据，返回 DataFrame

    index: MultiIndex [trade_date, stock_code]
    columns: open, high, low, close, volume, turnover

    - 未传 cfg / universe 或 universe=ALL：与历史行为一致，按日期整段拉全市场（供 daily_factor_values 等复用）。
    - 非 ALL：在 SQL 侧按股票池过滤，避免先全量进内存再筛（与 _filter_price_df_by_universe 口径一致）。
    """
    t0 = time.perf_counter()
    u = (
        normalize_universe_code(universe)
        if (universe and str(universe).strip())
        else "ALL"
    )
    use_sql_filter = cfg is not None and u != "ALL"
    logger.info(
        "_load_stock_daily 启动 config_file=%s start_date=%s end_date=%s universe=%s use_sql_filter=%s",
        config_file,
        start_date,
        end_date,
        u,
        use_sql_filter,
    )

    db_manager = get_db_manager(config_file=config_file)
    session = db_manager.get_session()

    try:
        base_select = """
        SELECT
            stock_code,
            trade_date,
            open,
            high,
            low,
            close,
            volume,
            turnover
        FROM stock_daily
        WHERE trade_date BETWEEN :start_date AND :end_date
        """

        if not use_sql_filter:
            logger.info("_load_stock_daily 分支=FULL_MARKET（不做 SQL 股票池过滤）")
            params: dict = {"start_date": start_date, "end_date": end_date}
            df = pd.read_sql(text(base_select), session.bind, params=params)
            log_stock_daily_banner(
                logger,
                where="factor_engine._load_stock_daily",
                mode="FULL_MARKET",
                start_date=start_date,
                end_date=end_date,
                n_stocks="ALL",
                n_batches=1,
                n_rows=len(df),
            )

        elif u == "STOCK":
            logger.info("_load_stock_daily 分支=STOCK（按 .SH/.SZ 后缀 SQL 过滤）")
            # 与 _filter_price_df_by_universe 中 STOCK 分支一致：仅 A 股 .SH/.SZ
            sql = (
                base_select
                + " AND (stock_code LIKE '%.SH' OR stock_code LIKE '%.SZ')"
            )
            params = {"start_date": start_date, "end_date": end_date}
            df = pd.read_sql(text(sql), session.bind, params=params)
            log_stock_daily_banner(
                logger,
                where="factor_engine._load_stock_daily",
                mode="SQL_STOCK_SUFFIX",
                start_date=start_date,
                end_date=end_date,
                n_stocks="-",
                n_batches=1,
                n_rows=len(df),
            )

        elif u in ("CUSTOM", "HS300", "ZZ500", "INDEX", "CSI", "ETF", "LOF", "FUTURES"):
            logger.info("_load_stock_daily 分支=UNIVERSE_IN_LIST（先解析股票池再分批 IN 查询） universe=%s", u)
            _auth_jq_if_configured(cfg, config_file=config_file)
            internal_codes, _, _, _ = resolve_universe_for_jq(
                cfg=cfg,
                end_date=end_date,
                section="factor_engine",
                universe_hint=u,
            )
            if not internal_codes:
                logger.warning(
                    "resolve_universe_for_jq 返回空股票池（universe=%s），stock_daily 不加载",
                    u,
                )
                log_stock_daily_banner(
                    logger,
                    where="factor_engine._load_stock_daily",
                    mode=f"EMPTY_POOL_{u}",
                    start_date=start_date,
                    end_date=end_date,
                    n_stocks=0,
                    n_batches=0,
                    n_rows=0,
                )
                return pd.DataFrame()

            # IN 列表过长时分批查询，避免单条 SQL 参数过多
            batch_size = 800
            frames: List[pd.DataFrame] = []
            sql_in = text(
                base_select + " AND stock_code IN :codes"
            ).bindparams(bindparam("codes", expanding=True))

            total_batches = max(1, (len(internal_codes) + batch_size - 1) // batch_size)
            logger.info(
                "_load_stock_daily 股票池解析完成 universe=%s n_codes=%d batch_size=%d total_batches=%d",
                u,
                len(internal_codes),
                batch_size,
                total_batches,
            )
            for i in range(0, len(internal_codes), batch_size):
                batch = internal_codes[i : i + batch_size]
                batch_no = i // batch_size + 1
                batch_t0 = time.perf_counter()
                part = pd.read_sql(
                    sql_in,
                    session.bind,
                    params={
                        "start_date": start_date,
                        "end_date": end_date,
                        "codes": batch,
                    },
                )
                frames.append(part)
                logger.info(
                    "_load_stock_daily 批次进度 universe=%s batch=%d/%d batch_codes=%d rows=%d elapsed=%.2fs",
                    u,
                    batch_no,
                    total_batches,
                    len(batch),
                    len(part),
                    time.perf_counter() - batch_t0,
                )

            df = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
            nb = total_batches
            log_stock_daily_banner(
                logger,
                where="factor_engine._load_stock_daily",
                mode=f"IN_universe_{u}",
                start_date=start_date,
                end_date=end_date,
                n_stocks=len(internal_codes),
                n_batches=nb,
                n_rows=len(df),
            )

        else:
            raise ValueError(f"不支持的 factor_engine.universe（_load_stock_daily）: {u}")

    finally:
        session.close()

    if df.empty:
        logger.warning(
            "_load_stock_daily 完成但无数据 universe=%s elapsed=%.2fs",
            u,
            time.perf_counter() - t0,
        )
        logger.warning(f"stock_daily 在 {start_date} ~ {end_date} 区间无数据")
        return df

    df["trade_date"] = pd.to_datetime(df["trade_date"])
    df = df.set_index(["trade_date", "stock_code"]).sort_index()
    logger.info(
        "_load_stock_daily 完成 universe=%s rows=%d elapsed=%.2fs",
        u,
        len(df),
        time.perf_counter() - t0,
    )

    return df


def _ma(series: pd.Series, window: int, m: int | None = None) -> pd.Series:
    """截面内按股票分组的简单移动平均

    兼容 alpha191 中 SMA/SMEAN 等 3 参数形式，这里先忽略 m，按简单 MA 处理。
    """
    ma = (
        series.groupby(level="stock_code")
        .rolling(window, min_periods=window)
        .mean()
        .reset_index(level=0, drop=True)
    )
    # 对齐原始索引，避免与原 series 比较时报 "Can only compare identically-labeled Series objects"
    return ma.reindex(series.index)


def _ref(series: pd.Series, n: int) -> pd.Series:
    """按股票分组向前平移 n 日"""
    return (
        series.groupby(level="stock_code")
        .shift(n)
    )


def _log(series: pd.Series) -> pd.Series:
    return np.log(series)


def _delta(x, n: int | None = None) -> pd.Series:
    """时间序列差分，对应 alpha191 的 DELTA(A, n)

    兼容两种调用形式：
    - DELTA(series, n)
    - DELTA((series, n))  # 由于 eval/括号问题可能被打包成 tuple
    """
    # 兼容 tuple 打包形式：DELTA(((expr, n))) 之类
    if n is None:
        if isinstance(x, tuple) and len(x) == 2:
            series, n = x
        else:
            raise TypeError("_delta 期望 (series, n) 或 (series, n) 形式的参数")
    else:
        series = x

    if not isinstance(series, pd.Series):
        raise TypeError("_delta 第一个参数必须是 pandas.Series")

    return series.groupby(level="stock_code").diff(int(n))


def _delay(x, n: int | None = None) -> pd.Series:
    """时间序列平移，对应 alpha191 的 DELAY(A, n)"""
    if n is None:
        if isinstance(x, tuple) and len(x) == 2:
            series, n = x
        else:
            raise TypeError("_delay 期望 (series, n) 或 (series, n) 形式的参数")
    else:
        series = x

    if not isinstance(series, pd.Series):
        raise TypeError("_delay 第一个参数必须是 pandas.Series")

    return series.groupby(level="stock_code").shift(int(n))


def _ts_sum(series: pd.Series, window: int) -> pd.Series:
    """时间序列滚动求和（按股票分组），对应 alpha191 的 TS_SUM"""
    summed = (
        series.groupby(level="stock_code")
        .rolling(window, min_periods=window)
        .sum()
        .reset_index(level=0, drop=True)
    )

    # 保证返回的 index 与原始 series 完全一致，避免后续比较时报
    # "Can only compare identically-labeled Series objects"
    return summed.reindex(series.index)


def _ts_max(series: pd.Series, window: int) -> pd.Series:
    """时间序列滚动最大值（按股票分组），对应 alpha191 的 TS_MAX"""
    maxed = (
        series.groupby(level="stock_code")
        .rolling(window, min_periods=window)
        .max()
        .reset_index(level=0, drop=True)
    )
    # 对齐原始索引，避免后续比较时报 index 不一致
    return maxed.reindex(series.index)


def _ts_min(series: pd.Series, window: int) -> pd.Series:
    """时间序列滚动最小值（按股票分组），对应 alpha191 的 TS_MIN"""
    mined = (
        series.groupby(level="stock_code")
        .rolling(window, min_periods=window)
        .min()
        .reset_index(level=0, drop=True)
    )
    # 对齐原始索引，避免后续比较时报 index 不一致
    return mined.reindex(series.index)


def _ts_rank(series: pd.Series, window: int) -> pd.Series:
    """时间窗口内 rank（按股票分组），对应 alpha191 TS_RANK

    实现：对每个股票 rolling(window)，在窗口内对数值做 rank，
    取窗口最后一个点的相对名次并归一到 0-1。
    """

    def _group_ts_rank(g: pd.Series) -> pd.Series:
        r = (
            g.rolling(window, min_periods=window)
            .apply(
                lambda s: s.rank(method="average").iloc[-1]
                / (len(s) if len(s) > 1 else 1),
                raw=False,
            )
        )
        return r

    out = (
        series.groupby(level="stock_code")
        .apply(_group_ts_rank)
        .reset_index(level=0, drop=True)
    )
    # 对齐原始索引，避免后续组合时报 index 不一致
    return out.reindex(series.index)


def _ts_argmax(series: pd.Series, window: int) -> pd.Series:
    """时间序列滚动最大值的位置（按股票分组），对应 alpha101 的 TS_ARGMAX"""
    argmaxed = (
        series.groupby(level="stock_code")
        .rolling(window, min_periods=window)
        .apply(np.argmax)
        .reset_index(level=0, drop=True) + 1
    )
    return argmaxed.reindex(series.index)


def _ts_argmin(series: pd.Series, window: int) -> pd.Series:
    """时间序列滚动最小值的位置（按股票分组），对应 alpha101 的 TS_ARGMIN"""
    argmined = (
        series.groupby(level="stock_code")
        .rolling(window, min_periods=window)
        .apply(np.argmin)
        .reset_index(level=0, drop=True) + 1
    )
    return argmined.reindex(series.index)


def _ts_sign_power(series: pd.Series, window: int) -> pd.Series:
    """时间序列滚动信号符号幂，对应 alpha101 的 SIGNEDPOWER"""
    def _group_ts_sign_power(g: pd.Series) -> pd.Series:
        return g.rolling(window, min_periods=window).apply(
            lambda s: np.sign(s.iloc[-1]) * (np.abs(s.iloc[-1]) ** window),
            raw=False,
        )

    sign_power = (
        series.groupby(level="stock_code")
        .apply(_group_ts_sign_power)
        .reset_index(level=0, drop=True)
    )
    return sign_power.reindex(series.index)


def _std(series: pd.Series, window: int | None = None) -> pd.Series:
    """时间序列滚动标准差（按股票分组），对应 alpha191 的 STD/STDDEV

    - STD(A, n)：过去 n 日滚动标准差；
    - STD(A)：若未给窗口，则用 expanding 标准差（从起始到当前）。
    """
    g = series.groupby(level="stock_code")
    if window is None:
        out = (
            g.expanding(min_periods=1)
            .std()
            .reset_index(level=0, drop=True)
        )
        return out.reindex(series.index)

    out = (
        g.rolling(window, min_periods=window)
        .std()
        .reset_index(level=0, drop=True)
    )
    return out.reindex(series.index)


def _kurt(series: pd.Series, window: int | None = None) -> pd.Series:
    """峰度：支持 rolling / expanding 两种模式"""
    g = series.groupby(level="stock_code")
    if window is None:
        out = (
            g.expanding(min_periods=1)
            .kurt()
            .reset_index(level=0, drop=True)
        )
        return out.reindex(series.index)

    out = (
        g.rolling(window, min_periods=window)
        .kurt()
        .reset_index(level=0, drop=True)
    )
    return out.reindex(series.index)


def _skew(series: pd.Series, window: int | None = None) -> pd.Series:
    """偏度：支持 rolling / expanding 两种模式"""
    g = series.groupby(level="stock_code")
    if window is None:
        out = (
            g.expanding(min_periods=1)
            .skew()
            .reset_index(level=0, drop=True)
        )
        return out.reindex(series.index)

    out = (
        g.rolling(window, min_periods=window)
        .skew()
        .reset_index(level=0, drop=True)
    )
    return out.reindex(series.index)


def _var(series: pd.Series, window: int | None = None) -> pd.Series:
    """方差：支持 rolling / expanding 两种模式"""
    g = series.groupby(level="stock_code")
    if window is None:
        out = (
            g.expanding(min_periods=1)
            .var()
            .reset_index(level=0, drop=True)
        )
        return out.reindex(series.index)

    out = (
        g.rolling(window, min_periods=window)
        .var()
        .reset_index(level=0, drop=True)
    )
    return out.reindex(series.index)


def _median(series: pd.Series, window: int | None = None) -> pd.Series:
    """中位数：支持 rolling / expanding 两种模式"""
    g = series.groupby(level="stock_code")
    if window is None:
        out = (
            g.expanding(min_periods=1)
            .median()
            .reset_index(level=0, drop=True)
        )
        return out.reindex(series.index)

    out = (
        g.rolling(window, min_periods=window)
        .median()
        .reset_index(level=0, drop=True)
    )
    return out.reindex(series.index)


def _pct(series: pd.Series, window: int) -> pd.Series:
    """滚动区间归一化到 [-1, 1]，对应 TS_PERCENT"""
    return ((series - _ts_min(series, window)) / (_ts_max(series, window) - _ts_min(series, window)) - 0.5) * 2.0


def _sum(series: pd.Series, window: int) -> pd.Series:
    """简单封装，方便 SUM(x, n) 写法，语义同 TS_SUM"""
    return _ts_sum(series, window)


def _abs(series: pd.Series) -> pd.Series:
    return series.abs()


def _pct_change(series: pd.Series, window: int | None = 1) -> pd.Series:
    return series.pct_change(int(window))


def _sign(series: pd.Series) -> pd.Series:
    """符号函数：>0 -> 1, <0 -> -1, ==0 -> 0"""
    return np.sign(series)


def _min(x, y) -> pd.Series:
    """逐点最小值，兼容 Series / 标量组合"""
    if isinstance(x, pd.Series) and isinstance(y, pd.Series):
        a, b = x.align(y)
    elif isinstance(x, pd.Series):
        a = x
        b = pd.Series(y, index=x.index)
    elif isinstance(y, pd.Series):
        a = pd.Series(x, index=y.index)
        b = y
    else:
        # 两个标量，返回标量 Series
        return pd.Series(np.minimum(x, y))

    return pd.concat([a, b], axis=1).min(axis=1)


def _max(x, y) -> pd.Series:
    """逐点最大值，兼容 Series / 标量组合"""
    if isinstance(x, pd.Series) and isinstance(y, pd.Series):
        a, b = x.align(y)
    elif isinstance(x, pd.Series):
        a = x
        b = pd.Series(y, index=x.index)
    elif isinstance(y, pd.Series):
        a = pd.Series(x, index=y.index)
        b = y
    else:
        return pd.Series(np.maximum(x, y))

    return pd.concat([a, b], axis=1).max(axis=1)


def _pow(x: pd.Series, y) -> pd.Series:
    """幂函数，对标 alpha191 的 POW/POWER"""
    return np.power(x, y)


def _scale(series: pd.Series, k: float = 1.0) -> pd.Series:
    """按 alpha191 习惯，把序列缩放到绝对值和为 k（默认 1）"""
    abs_sum = series.abs().groupby(level="trade_date").transform("sum")
    return series / abs_sum * k


def _if(cond, x, y):
    """条件选择，对应 alpha191 里的 IF 或我们转换出来的三目表达式

    注意：保持返回值为 pandas.Series，方便后续继续做 groupby/rolling 等操作。
    """
    # 统一用 numpy.where 计算，然后包装回 Series，彻底避免 BlockManager 的 dtype 拼接问题。
    # 规则：
    # - 优先用 cond 的索引，其次用 x/y 的索引；若都不是 Series，则返回简单一维 Series。

    # 1) 纯标量 / ndarray 场景：不依赖 index，直接返回简单 Series
    if not isinstance(cond, pd.Series) and not isinstance(x, pd.Series) and not isinstance(y, pd.Series):
        return pd.Series(np.where(cond, x, y))

    # 2) 确定目标索引（优先 cond，然后 x，再 y）
    idx = None
    if isinstance(cond, pd.Series):
        idx = cond.index
    if isinstance(x, pd.Series) and idx is None:
        idx = x.index
    if isinstance(y, pd.Series) and idx is None:
        idx = y.index

    if idx is None:
        # 理论上走不到这里，兜底一下
        return pd.Series(np.where(cond, x, y))

    # 3) 构造对齐到 idx 的 ndarray
    if isinstance(cond, pd.Series):
        cond_arr = cond.reindex(idx).to_numpy()
    else:
        cond_arr = np.full(len(idx), bool(cond))

    def _to_arr(v):
        if isinstance(v, pd.Series):
            return v.reindex(idx).to_numpy()
        return np.full(len(idx), v)

    x_arr = _to_arr(x)
    y_arr = _to_arr(y)

    out = np.where(cond_arr, x_arr, y_arr)
    return pd.Series(out, index=idx)


def _if_elif_else(cond, x, cond2, y, z):
    """三元条件：if cond then x elif cond2 then y else z"""
    return _if(cond, x, _if(cond2, y, z))


def _if_elif_elif_else(cond, x, cond2, y, cond3, z, w):
    """四元条件：if cond then x elif cond2 then y elif cond3 then z else w"""
    return _if(cond, x, _if(cond2, y, _if(cond3, z, w)))


def _rank(series: pd.Series) -> pd.Series:
    # 截面 rank，0-1 归一
    df = series.to_frame("v")

    def _cs_rank(g: pd.DataFrame) -> pd.DataFrame:
        s = g["v"]
        r = s.rank(method="average")
        g["v"] = (r - 1) / (len(r) - 1) if len(r) > 1 else 0.0
        return g

    df = df.groupby(level="trade_date", group_keys=False).apply(_cs_rank)
    return df["v"]

def _corr(x: pd.Series, y: pd.Series, window: int) -> pd.Series:
    df_xy = pd.concat({"x": x, "y": y}, axis=1)

    def _corr_group(g: pd.DataFrame) -> pd.Series:
        return g["x"].rolling(window, min_periods=window).corr(g["y"])

    out = (
        df_xy.groupby(level="stock_code")
        .apply(_corr_group)
        .reset_index(level=0, drop=True)
    )
    # 对齐原始索引，避免比较/组合时报 "Can only compare identically-labeled Series objects"
    return out.reindex(x.index)


def _covariance(x: pd.Series, y: pd.Series, window: int) -> pd.Series:
    """时间序列滚动协方差，对应 alpha191 的 COVIANCE(A, B, n)"""
    df_xy = pd.concat({"x": x, "y": y}, axis=1)

    def _cov_group(g: pd.DataFrame) -> pd.Series:
        return g["x"].rolling(window, min_periods=window).cov(g["y"])

    out = (
        df_xy.groupby(level="stock_code")
        .apply(_cov_group)
        .reset_index(level=0, drop=True)
    )
    return out.reindex(x.index)


def _prod(series: pd.Series, window: int) -> pd.Series:
    """时间序列滚动累乘，对应 alpha191 的 PROD(A, n)"""
    out = (
        series.groupby(level="stock_code")
        .rolling(window, min_periods=window)
        .apply(lambda s: np.prod(s.values), raw=False)
        .reset_index(level=0, drop=True)
    )
    return out.reindex(series.index)


def _count(cond: pd.Series, window: int) -> pd.Series:
    """时间序列条件计数：过去 n 日内 condition 为真次数，对应 COUNT(condition, n)"""
    # cond 可能是 bool / 0-1 数值，也可能是纯标量 True/False
    if isinstance(cond, pd.Series):
        s = cond.astype(float)
        out = (
            s.groupby(level="stock_code")
            .rolling(window, min_periods=window)
            .sum()
            .reset_index(level=0, drop=True)
        )
        return out.reindex(cond.index)

    # 标量条件：直接返回常数 Series，避免 'int' object has no attribute 'astype'
    val = float(bool(cond))
    return pd.Series(dtype=float)


def _regbeta(a: pd.Series, b: pd.Series, window: int) -> pd.Series:
    """滚动回归系数 beta(A 对 B)，对应 REGBETA(A, B, n)

    实现：对每只股票，按窗口 n 计算：
        beta = cov(A, B) / var(B)
    """
    df_ab = pd.concat({"a": a, "b": b}, axis=1)

    def _beta_group(g: pd.DataFrame) -> pd.Series:
        a_s = g["a"]
        b_s = g["b"]
        cov = a_s.rolling(window, min_periods=window).cov(b_s)
        var = b_s.rolling(window, min_periods=window).var()
        beta = cov / var.replace(0, np.nan)
        return beta

    out = (
        df_ab.groupby(level="stock_code")
        .apply(_beta_group)
        .reset_index(level=0, drop=True)
    )
    return out.reindex(a.index)


def _regresi(a: pd.Series, b: pd.Series, window: int) -> pd.Series:
    """滚动回归残差 RESI(A 对 B)，对应 REGRESI(A, B, n)

    对每个窗口，先算 beta、alpha，再返回 A_t - alpha - beta * B_t。
    """
    df_ab = pd.concat({"a": a, "b": b}, axis=1)

    def _resid_group(g: pd.DataFrame) -> pd.Series:
        a_s = g["a"]
        b_s = g["b"]
        roll = a_s.rolling(window, min_periods=window)

        mean_a = roll.mean()
        mean_b = b_s.rolling(window, min_periods=window).mean()
        cov = a_s.rolling(window, min_periods=window).cov(b_s)
        var = b_s.rolling(window, min_periods=window).var()
        beta = cov / var.replace(0, np.nan)
        alpha = mean_a - beta * mean_b
        resid = a_s - alpha - beta * b_s
        return resid

    return (
        df_ab.groupby(level="stock_code")
        .apply(_resid_group)
        .reset_index(level=0, drop=True)
    )


def _sumif(a: pd.Series, cond: pd.Series, window: int) -> pd.Series:
    """条件求和，对应 SUMIF(A, n, condition)

    简化实现：对过去 n 日内 cond 为真位置的 A 求和。
    """
    masked = a.where(cond.astype(bool), 0.0)
    return _ts_sum(masked, window)


def _wma(series: pd.Series, window: int) -> pd.Series:
    """加权移动平均：与 others/factor_base_func.py 的 WMA(A, n) 语义对齐。"""
    out = (
        series.groupby(level="stock_code")
        .apply(lambda s: s.ewm(alpha=float(1 / window), ignore_na=True).mean())
        .reset_index(level=0, drop=True)
    )
    return out.reindex(series.index)


def _sma(series: pd.Series, n: int, m: int) -> pd.Series:
    """加权移动平均：与 others/factor_base_func.py 的 SMA(A, n, m) 语义对齐。"""
    out = (
        series.groupby(level="stock_code")
        .apply(lambda s: s.ewm(alpha=float(m / n), ignore_na=True).mean())
        .reset_index(level=0, drop=True)
    )
    return out.reindex(series.index)


def _hma(series: pd.Series, window: int) -> pd.Series:
    """半衰期加权移动平均：与 others/factor_base_func.py 的 HMA(A, h) 语义对齐。"""
    out = (
        series.groupby(level="stock_code")
        .apply(lambda s: s.ewm(halflife=int(window), ignore_na=True).mean())
        .reset_index(level=0, drop=True)
    )
    return out.reindex(series.index)


def _ema(series: pd.Series, period: int = 10) -> pd.Series:
    """指数移动平均：与 others/factor_base_func.py 的 EMA(df, period) 语义对齐。"""
    out = (
        series.groupby(level="stock_code")
        .apply(lambda s: s.ewm(span=int(period), ignore_na=True).mean())
        .reset_index(level=0, drop=True)
    )
    return out.reindex(series.index)


def _decaylinear(series: pd.Series, window: int) -> pd.Series:
    """线性衰减加权平均，对应 DECAYLINEAR(A, d)，权重 d, d-1, ..., 1"""

    weights = np.arange(1, window + 1, dtype=float)
    weights = weights / weights.sum()

    def _decay_group(s: pd.Series) -> pd.Series:
        def _decay_window(x: pd.Series) -> float:
            if len(x) < window:
                return np.nan
            return float(np.dot(x.values, weights))

        return (
            s.rolling(window, min_periods=window)
            .apply(_decay_window, raw=False)
        )

    out = (
        series.groupby(level="stock_code")
        .apply(_decay_group)
        .reset_index(level=0, drop=True)
    )
    return out.reindex(series.index)


def _filter(a: pd.Series, cond: pd.Series) -> pd.Series:
    """简单实现 FILTER(A, condition)：不满足条件的位置置为 NaN"""
    return a.where(cond.astype(bool))


def _highday(series: pd.Series, window: int) -> pd.Series:
    """HIGHDAY(A, n)：过去 n 日内最大值距离当前的间隔"""

    def _highday_group(s: pd.Series) -> pd.Series:
        def _idx(x: pd.Series) -> float:
            if len(x) < window:
                return np.nan
            # 最近一天是位置 window-1
            return float((window - 1) - int(np.argmax(x.values)))

        return (
            s.rolling(window, min_periods=window)
            .apply(_idx, raw=False)
        )

    return (
        series.groupby(level="stock_code")
        .apply(_highday_group)
        .reset_index(level=0, drop=True)
    )


def _lowday(series: pd.Series, window: int) -> pd.Series:
    """LOWDAY(A, n)：过去 n 日内最小值距离当前的间隔"""

    def _lowday_group(s: pd.Series) -> pd.Series:
        def _idx(x: pd.Series) -> float:
            if len(x) < window:
                return np.nan
            return float((window - 1) - int(np.argmin(x.values)))

        return (
            s.rolling(window, min_periods=window)
            .apply(_idx, raw=False)
        )

    return (
        series.groupby(level="stock_code")
        .apply(_lowday_group)
        .reset_index(level=0, drop=True)
    )


def _sumac(series: pd.Series, window: int) -> pd.Series:
    """SUMAC(A, n)：前 n 项累加，这里按股票做 expanding 累加"""
    return (
        series.groupby(level="stock_code")
        .expanding(min_periods=1)
        .sum()
        .reset_index(level=0, drop=True)
    )


def compute_factor_values(formula: str, price_df: pd.DataFrame) -> pd.Series:
    """基于受限 eval 的因子 DSL 计算因子值

    允许的标识符（字段 / 函数）以 `factor_engine.factor_dsl_allowlist` 为准，
    与下方 `locals_dict` 键集合保持一致（运行时断言）。

    典型能力概览：
    - 行情字段：open, high, low, close, volume, turnover 及 VWAP/RET 等衍生序列
    - Alpha191 风格算子：CORR/RANK/DELTA/LOG/TS_* / IF / MIN / MAX 等（大小写别名并存）
    - 运算：+ - * / 与括号
    """
    # 衍生字段：VWAP / RET / 市场因子 / 各类中间变量（DTM / DBM / TR / HD / LD 等）
    vwap = price_df["turnover"] / price_df["volume"]

    open_ = price_df["open"]
    high = price_df["high"]
    low = price_df["low"]
    close = price_df["close"]

    # 日收益率：按股票分组的 close_pct_change（RET）
    ret = close.groupby(level="stock_code").pct_change()

    # 前一日价格：用于 RET / DTM / DBM / TR / HD / LD 等
    prev_open = open_.groupby(level="stock_code").shift(1)
    prev_close = close.groupby(level="stock_code").shift(1)
    prev_high = high.groupby(level="stock_code").shift(1)
    prev_low = low.groupby(level="stock_code").shift(1)

    # DTM: (OPEN<=DELAY(OPEN,1)?0:MAX((HIGH-OPEN),(OPEN-DELAY(OPEN,1))))
    cond_dtm_zero = (open_ <= prev_open) | prev_open.isna()
    dtm_candidate1 = high - open_
    dtm_candidate2 = open_ - prev_open
    dtm_max = pd.concat([dtm_candidate1, dtm_candidate2], axis=1).max(axis=1)
    dtm = pd.Series(0.0, index=price_df.index)
    dtm[~cond_dtm_zero] = dtm_max[~cond_dtm_zero]

    # DBM: (OPEN>=DELAY(OPEN,1)?0:MAX((OPEN-LOW),(OPEN-DELAY(OPEN,1))))
    cond_dbm_zero = (open_ >= prev_open) | prev_open.isna()
    dbm_candidate1 = open_ - low
    dbm_candidate2 = open_ - prev_open
    dbm_max = pd.concat([dbm_candidate1, dbm_candidate2], axis=1).max(axis=1)
    dbm = pd.Series(0.0, index=price_df.index)
    dbm[~cond_dbm_zero] = dbm_max[~cond_dbm_zero]

    # TR: MAX(MAX(HIGH-LOW,ABS(HIGH-DELAY(CLOSE,1))),ABS(LOW-DELAY(CLOSE,1)))
    tr_range1 = high - low
    tr_range2 = (high - prev_close).abs()
    tr_range3 = (low - prev_close).abs()
    tr = pd.concat([tr_range1, tr_range2, tr_range3], axis=1).max(axis=1)

    # HD: HIGH-DELAY(HIGH,1)
    hd = high - prev_high

    # LD: DELAY(LOW,1)-LOW
    ld = prev_low - low

    # 占位的三因子：MKT、SMB、HML（未来可从外部因子表接入真实值）
    zeros_factor = pd.Series(0.0, index=price_df.index)

    # SEQUENCE(n)：按文档含义代表“时间序列 1~n”，这里近似为每只股票自己的交易日序列 1,2,...
    seq_index = price_df.groupby(level="stock_code").cumcount() + 1

    locals_dict = {
        "open": open_,
        "high": high,
        "low": low,
        "close": close,
        "volume": price_df["volume"],
        "turnover": price_df["turnover"],
        "VWAP": vwap,
        "vwap": vwap,
        "RET": ret,
        "ret": ret,
        "MKT": zeros_factor,
        "SMB": zeros_factor,
        "HML": zeros_factor,
        "BANCHMARKINDEXCLOSE": zeros_factor,
        "BANCHMARKINDEXOPEN": zeros_factor,

        # 时间序列辅助：SEQUENCE(n) —— 近似为每只股票的交易日序列
        "SEQUENCE": lambda n, s=seq_index: s,
        # DTM / DBM / TR / HD / LD：Alpha 相关文档里出现的中间量，这里按文档定义真实计算
        "DTM": dtm,
        "DBM": dbm,
        "TR": tr,
        "HD": hd,
        "LD": ld,
        "MA": _ma,
        "REF": _ref,

        # Alpha191 风格算子
        "LOG": _log,
        "DELTA": _delta,
        "RANK": _rank,
        "CORR": _corr,
        "TS_SUM": _ts_sum,
        "TS_MAX": _ts_max,
        "TS_MIN": _ts_min,
        "TS_RANK": _ts_rank,
        "STD": _std,
        "STDDEV": _std,
        "SUM": _sum,
        "ABS": _abs,
        "SIGN": _sign,
        "MIN": _min,
        "MAX": _max,
        "POW": _pow,
        "POWER": _pow,
        "SCALE": _scale,
        "IF": _if,
        "COVIANCE": _covariance,
        "COVARIANCE": _covariance,
        "SMEAN": _ma,
        "PROD": _prod,
        "COUNT": _count,
        "REGBETA": _regbeta,
        "REGRESI": _regresi,
        "SUMIF": _sumif,
        "WMA": _wma,
        "DECAYLINEAR": _decaylinear,
        "FILTER": _filter,
        "HIGHDAY": _highday,
        "LOWDAY": _lowday,
        "SUMAC": _sumac,
        "DELAY": _delay,
        "TS_CORR": _corr,
        "TS_STD": _std,
        "TS_MEAN": _ma,
        "TS_ARGMAX": _ts_argmax,
        "TS_ARGMIN": _ts_argmin,
        "SIGNEDPOWER": _ts_sign_power,
        "TWO_CONDITION": _if,
        "THREE_CONDITION": _if_elif_else,
        "FOUR_CONDITION": _if_elif_elif_else,
        "TS_SUMIF": _sumif,
        "TS_COV": _covariance,
        "TS_RANK_PERCENT": _ts_rank,
        "TS_PROD": _prod,
        "TS_COUNT": _count,
        "TS_REGBETA": _regbeta,
        "TS_KURT": _kurt,
        "TS_SKEW": _skew,
        "TS_VAR": _var,
        "SMA": _sma,
        "EMA": _ema,
        "HMA": _hma,
        "TS_MEDIAN": _median,
        "TS_PERCENT": _pct,
        "PCT_CHANGE": _pct_change,
        "DECAY_LINEAR": _decaylinear,

        # 大小写都兼容 / 兼顾内部 DSL 与 alpha191 原始大小写
        "log": _log,
        "delta": _delta,
        "rank": _rank,
        "corr": _corr,
        "ts_sum": _ts_sum,
        "ts_max": _ts_max,
        "ts_min": _ts_min,
        "ts_rank": _ts_rank,
        "std": _std,
        "stddev": _std,
        "sum": _sum,
        "abs": _abs,
        "sign": _sign,
        "min": _min,
        "max": _max,
        "pow": _pow,
        "power": _pow,
        "scale": _scale,
        "if": _if,
        "covariance": _covariance,
        "smean": _ma,
        "prod": _prod,
        "count": _count,
        "regbeta": _regbeta,
        "regresi": _regresi,
        "sumif": _sumif,
        "wma": _wma,
        "decaylinear": _decaylinear,
        "filter": _filter,
        "highday": _highday,
        "lowday": _lowday,
        "sumac": _sumac,
        "dtm": dtm,
        "dbm": dbm,
        "tr": tr,
        "hd": hd,
        "ld": ld,
        "banchmarkindexclose": zeros_factor,
        "banchmarkindexopen": zeros_factor,
        "sequence": lambda n, s=seq_index: s,
        "returns": ret,
        "delay": _delay,
        "ts_corr": _corr,
        "ts_argmax": _ts_argmax,
        "ts_argmin": _ts_argmin,
        "four_condition": _if_elif_elif_else,
    }

    # 与 factor_dsl_allowlist 保持单一事实来源：locals 键集必须完全一致
    assert_locals_dict_keys_match_allowlist(locals_dict.keys())

    # 使用受限 eval，仅提供我们需要的局部变量
    result = eval(formula, {"__builtins__": {}}, locals_dict)  # noqa: S307
    if not isinstance(result, pd.Series):
        raise ValueError("公式计算结果不是 pandas.Series")
    return result


def winsorize_and_standardize(series: pd.Series) -> pd.Series:
    """按文档约定进行去极值 + 标准化

    - 去极值：按当日截面 1%–99% 分位数剪裁
    - 标准化：按当日截面 Z-score
    """
    df = series.to_frame("factor_value").copy()

    # 截面去极值
    def _winsorize(group: pd.DataFrame) -> pd.DataFrame:
        s = group["factor_value"]
        if s.isna().all():
            return group
        q01 = s.quantile(0.01)
        q99 = s.quantile(0.99)
        group["factor_value"] = s.clip(lower=q01, upper=q99)
        return group

    df = df.groupby(level="trade_date", group_keys=False).apply(_winsorize)

    # 截面标准化
    def _zscore(group: pd.DataFrame) -> pd.DataFrame:
        s = group["factor_value"]
        mean = s.mean()
        std = s.std()
        if std == 0 or pd.isna(std):
            group["factor_value"] = 0.0
        else:
            group["factor_value"] = (s - mean) / std
        return group

    df = df.groupby(level="trade_date", group_keys=False).apply(_zscore)

    return df["factor_value"]


def _dedupe_factor_id_sequence(override: Sequence[str]) -> List[str]:
    """P1 / worker：对显式 factor_id 列表去空白、去重且保序，供 factor_ids_override 使用。"""
    out: List[str] = []
    seen = set()
    for x in override:
        s = str(x).strip()
        if s and s not in seen:
            seen.add(s)
            out.append(s)
    return out


def run_factor_engine(
    config_file: str = "config.ini",
    *,
    start_date_override: Optional[str] = None,
    end_date_override: Optional[str] = None,
    publish_start_date_override: Optional[str] = None,
    batch_id_override: Optional[str] = None,
    stage_override: Optional[str] = None,
    is_rebase_override: Optional[bool] = None,
    # 与 [factor_engine] 中 factor_ids / universe 的显式覆写，避免为每条任务写临时 ini。
    # - factor_ids_override 为 None：从配置文件读取（空串表示全量 ALL，保持旧语义）。
    # - factor_ids_override 非 None：必须得到至少一个 factor_id，否则 ValueError；忽略 ini 的 factor_ids。
    # - universe_override 为 None：从配置文件读取；非 None 则经 normalize 后使用，并忽略 ini 的 universe。
    factor_ids_override: Optional[Sequence[str]] = None,
    universe_override: Optional[str] = None,
    # skip_if_batch_csv_record_exists_override：None 读 ini；True/False 显式覆盖 skip_if_batch_csv_record_exists。
    skip_if_batch_csv_record_exists_override: Optional[bool] = None,
    # daily_csv_mode：日更语义，CSV 写入 factor_values/daily/by_universe/... ，factor_value_files.artifact_type=daily_csv，
    # 与同仓库 factor_export_cos 中 daily_override_batch 对齐。要求 publish_start_date 与 end_date 同一天；
    # start_date 可更早（回看/warmup），与 incremental 单笔单日任务一致。
    daily_csv_mode: bool = False,
) -> None:
    """
    因子主计算（含行情加载、算子、落 CSV、回写 factor_value_files）。

    与 P1 / factor_pipeline_job 对接时，推荐优先传 ``factor_ids_override`` / ``universe_override``，
    与单条 job 参数对齐；其余 [factor_engine] 与 [jq] 等仍来自 ``config_file`` 根配置。

    开关 ``skip_if_batch_csv_record_exists`` 默认开启：在计算前查询 ``factor_value_files``，
    当前任务对应的 ``batch_csv`` / ``daily_csv``（daily_csv_mode 时按 trade_date）索引键，
    只要已存在任意一行则跳过该因子不落 CSV。
    配置文件或旧键设为 false（或 CLI ``--no-skip-if-batch-csv-record-exists``）可强制重算。
    （若启用且同键多条，会先 INFO 跳过并额外 WARNING。）
    """
    logger.info(
        "启动 factor_engine_runner daily_csv_mode=%s",
        bool(daily_csv_mode),
    )

    cfg = Config(config_file=config_file)

    start_date = start_date_override or cfg.get("factor_engine", "start_date", fallback="2024-01-01")
    end_date = end_date_override or cfg.get(
        "factor_engine",
        "end_date",
        fallback=datetime.now().strftime("%Y-%m-%d"),
    )
    if publish_start_date_override is not None:
        publish_start_date = publish_start_date_override
    elif daily_csv_mode:
        # 日报/单日任务：默认以区间右端点为发布日与 trade_date（左端点为加载/warmup 起点）。
        publish_start_date = end_date
    else:
        publish_start_date = start_date

    if daily_csv_mode:
        d_pub = date.fromisoformat(str(publish_start_date).strip()[:10])
        d_end = date.fromisoformat(str(end_date).strip()[:10])
        if d_pub != d_end:
            raise ValueError(
                f"daily_csv_mode 要求发布日为单日区间：publish_start_date ({d_pub}) 须等于 end_date ({d_end})"
            )

    if factor_ids_override is not None:
        factor_ids = _dedupe_factor_id_sequence(factor_ids_override)
        if not factor_ids:
            raise ValueError(
                "factor_ids_override 经去重后为空：请传至少一个 factor_id，"
                "或改为 factor_ids_override=None 以使用配置文件中的 [factor_engine].factor_ids"
            )
        logger.info("使用参数 factor_ids_override，忽略 [factor_engine].factor_ids 原文")
    else:
        factor_ids_raw = cfg.get("factor_engine", "factor_ids", fallback="").strip()
        factor_ids = [
            fid.strip()
            for fid in factor_ids_raw.split(",")
            if fid.strip()
        ]

    if universe_override is not None:
        u0 = str(universe_override).strip()
        if not u0:
            raise ValueError(
                "universe_override 只含空白不合法；请传 None 使用 [factor_engine].universe 或传有效域代码"
            )
        universe = normalize_universe_code(u0)
        logger.info("使用参数 universe_override，忽略 [factor_engine].universe 原文")
    else:
        universe = normalize_universe_code(
            cfg.get("factor_engine", "universe", fallback="ALL")
        )

    batch_id = (batch_id_override or cfg.get("factor_engine", "batch_id", fallback="")).strip()
    stage = (
        (stage_override or cfg.get("factor_engine", "stage", fallback="candidate") or "candidate")
        .strip()
        .lower()
    )
    is_rebase_cfg = bool(cfg.getboolean("factor_engine", "is_rebase", fallback=False))
    is_rebase = is_rebase_override if is_rebase_override is not None else is_rebase_cfg

    if not batch_id:
        # 默认批次号：inc_YYYYMMDD；重算模式则前缀 rebase_。
        batch_prefix = "rebase" if is_rebase else "inc"
        batch_id = f"{batch_prefix}_{end_date.replace('-', '')}"

    if stage not in ("candidate", "production", "deprecated"):
        raise ValueError(f"配置错误：factor_engine.stage 不合法（{stage}）")

    # 优先读新键 skip_if_batch_csv_record_exists；若无则兼容旧键 skip_if_batch_csv_duplicate；均无则默认「开」。
    if skip_if_batch_csv_record_exists_override is None:
        v = cfg.getboolean("factor_engine", "skip_if_batch_csv_record_exists", fallback=None)
        if v is None:
            v = cfg.getboolean("factor_engine", "skip_if_batch_csv_duplicate", fallback=None)
        if v is None:
            v = True
        skip_if_batch_csv_record_exists = bool(v)
    else:
        skip_if_batch_csv_record_exists = bool(skip_if_batch_csv_record_exists_override)

    # 黑名单：配置里可选的 skip_factor_ids，用逗号分隔
    skip_ids_raw = cfg.get("factor_engine", "skip_factor_ids", fallback="").strip()
    skip_factor_ids: List[str] = [
        fid.strip()
        for fid in skip_ids_raw.split(",")
        if fid.strip()
    ]

    logger.info(
        f"配置 - start_date={start_date}, end_date={end_date}, publish_start_date={publish_start_date}, "
        f"factor_ids={factor_ids or 'ALL'}, universe={universe}, "
        f"batch_id={batch_id}, stage={stage}, is_rebase={is_rebase}, "
        f"skip_if_batch_csv_record_exists={skip_if_batch_csv_record_exists}"
    )

    all_factors = load_all_factors()
    if not all_factors:
        logger.error("未解析到任何因子定义，退出")
        return

    # 过滤需要计算的因子
    if factor_ids:
        factors = [f for f in all_factors if f.factor_id in factor_ids]
        missing = set(factor_ids) - {f.factor_id for f in factors}
        if missing:
            logger.warning(f"以下因子ID在因子文档中未找到: {missing}")
    else:
        factors = all_factors

    if skip_factor_ids:
        before = len(factors)
        factors = [f for f in factors if f.factor_id not in skip_factor_ids]
        skipped = before - len(factors)
        if skipped:
            logger.info(
                f"根据配置 skip_factor_ids 跳过 {skipped} 个因子: {sorted(skip_factor_ids)}"
            )

    compute_workers_raw = str(
        cfg.get("factor_engine", "compute_workers", fallback="0")
    ).strip()
    try:
        compute_workers = int(compute_workers_raw) if compute_workers_raw else 0
    except ValueError:
        compute_workers = 0

    if compute_workers <= 0:
        compute_workers = min((os.cpu_count() or 1), 8)

    logger.info(
        "本次将计算 %s 个因子（仅多进程模式，compute_workers=%s）",
        len(factors),
        compute_workers,
    )

    # 拉行情：非 ALL 时在 SQL 侧按股票池过滤，避免全市场进内存（见 _load_stock_daily）
    price_df = _load_stock_daily(
        config_file=config_file,
        start_date=start_date,
        end_date=end_date,
        cfg=cfg,
        universe=universe,
    )
    if price_df.empty:
        logger.error("行情数据为空，无法计算因子")
        return

    db_manager = get_db_manager(config_file=config_file)
    session = db_manager.get_session()
    project_root = Path(__file__).resolve().parents[2]

    try:
        compute_factor_tasks: List[Tuple[str, str, str]] = []

        for factor in factors:
            logger.info(f"开始计算因子: {factor.factor_id} - {factor.factor_name}")

            # 可选：若 factor_value_files 已存在当前任务索引行，则跳过计算（便于幂等重跑）。
            if skip_if_batch_csv_record_exists:
                if daily_csv_mode:
                    td_key = date.fromisoformat(str(end_date).strip()[:10])
                    row_ids = _factor_value_files_daily_csv_ids_for_trade_date(
                        session,
                        factor_id=factor.factor_id,
                        universe=universe,
                        trade_date=td_key,
                    )
                    if len(row_ids) >= 1:
                        logger.info(
                            "跳过因子计算：factor_value_files 已存在 daily_csv 索引记录。"
                            "factor_id=%s universe=%s trade_date=%s row_count=%s ids=%s",
                            factor.factor_id,
                            universe,
                            td_key.isoformat(),
                            len(row_ids),
                            row_ids,
                        )
                        if len(row_ids) > 1:
                            logger.warning(
                                "factor_value_files 同一 daily_csv 键存在多条记录（数据异常，应唯一）：ids=%s",
                                row_ids,
                            )
                        continue
                else:
                    ds_key = date.fromisoformat(str(publish_start_date).strip()[:10])
                    de_key = date.fromisoformat(str(end_date).strip()[:10])
                    row_ids = _factor_value_files_batch_csv_ids_for_job_key(
                        session,
                        factor_id=factor.factor_id,
                        universe=universe,
                        date_start=ds_key,
                        date_end=de_key,
                    )
                    if len(row_ids) >= 1:
                        logger.info(
                            "跳过因子计算：factor_value_files 已存在 batch_csv 索引记录。"
                            "factor_id=%s universe=%s date_start=%s date_end=%s row_count=%s ids=%s",
                            factor.factor_id,
                            universe,
                            ds_key.isoformat(),
                            de_key.isoformat(),
                            len(row_ids),
                            row_ids,
                        )
                        if len(row_ids) > 1:
                            logger.warning(
                                "factor_value_files 同一 batch_csv 自然键存在多条记录（数据异常，应唯一）：ids=%s",
                                row_ids,
                            )
                        continue

            # 计算前先做公式静态校验：仅将“可翻译”的公式送入并行计算队列。
            try:
                validate_factor_dsl_formula(factor.formula)
            except Exception as e:
                logger.error(
                    "跳过因子：公式校验失败（factor_id=%s factor_name=%s err=%s）",
                    factor.factor_id,
                    factor.factor_name,
                    e,
                )
                continue

            compute_factor_tasks.append(
                (factor.factor_id, factor.factor_name, factor.formula)
            )

        # 计算阶段：固定多进程，不再降级串行。
        computed_result_map: dict = {}
        compute_order_factor_ids: List[str] = [x[0] for x in compute_factor_tasks]

        if compute_factor_tasks:
            logger.info(
                "开始多进程计算，共 %s 个任务，workers=%s",
                len(compute_factor_tasks),
                compute_workers,
            )
            try:
                with concurrent.futures.ProcessPoolExecutor(
                    max_workers=compute_workers,
                    initializer=_init_factor_compute_worker,
                    initargs=(price_df,),
                ) as executor:
                    future_map = {
                        executor.submit(_compute_factor_processed_series_worker, task): task[0]
                        for task in compute_factor_tasks
                    }

                    completed_count = 0
                    total_count = len(future_map)

                    # 终端用 tqdm 展示细粒度进度；日志文件则写里程碑进度，避免动态刷新字符污染日志。
                    progress_iter = tqdm(
                        concurrent.futures.as_completed(future_map),
                        total=total_count,
                        desc="factor compute",
                        disable=not sys.stderr.isatty(),
                    )

                    for future in progress_iter:
                        factor_id_ret, factor_name_ret, processed_series, error_message, elapsed = future.result()
                        completed_count += 1

                        if (completed_count % 20 == 0) or (completed_count == total_count):
                            logger.info(
                                "并行计算进度：%s/%s（%.1f%%）",
                                completed_count,
                                total_count,
                                (completed_count / total_count) * 100.0,
                            )

                        if error_message:
                            logger.error(
                                "计算因子失败（并行）：factor_id=%s factor_name=%s elapsed=%.3fs err=%s",
                                factor_id_ret,
                                factor_name_ret,
                                elapsed,
                                error_message,
                            )
                            continue

                        computed_result_map[factor_id_ret] = (factor_name_ret, processed_series)
                        logger.info(
                            "计算因子完成（并行）：factor_id=%s factor_name=%s elapsed=%.3fs",
                            factor_id_ret,
                            factor_name_ret,
                            elapsed,
                        )
            except Exception as e:
                logger.error(
                    "多进程计算阶段异常，本批次不再串行回退。err=%s",
                    e,
                )

        for factor_id in compute_order_factor_ids:
            if factor_id not in computed_result_map:
                continue

            factor_name, processed_series = computed_result_map[factor_id]

            # 简单输出前几行结果用于检查
            df_out = processed_series.to_frame("factor_value").reset_index()
            # 增量模式下 start_date 可能是 warmup 回看起点；发布时仅保留业务区间 publish_start_date~end_date。
            df_out["trade_date"] = pd.to_datetime(df_out["trade_date"])
            df_out = df_out[
                (df_out["trade_date"] >= pd.Timestamp(publish_start_date))
                & (df_out["trade_date"] <= pd.Timestamp(end_date))
            ].copy()
            logger.info(
                f"因子 {factor_id} 样例数据（前5行）:\n"
                f"{df_out.head().to_string(index=False)}"
            )

            # 导出 CSV：batch 沿用 by_universe 区间文件名；daily_csv_mode 与同仓库 daily_factor_values 路径一致。
            publish_iso = str(publish_start_date).strip()[:10]
            if daily_csv_mode:
                output_dir = os.path.join(
                    "factor_values",
                    "daily",
                    "by_universe",
                    universe,
                    publish_iso,
                )
                csv_name = f"{factor_id}.csv"
            else:
                output_dir = os.path.join("factor_values", "by_universe", universe)
                csv_name = (
                    f"{factor_id}_{universe}_{publish_start_date}_{end_date}.csv"
                    .replace(":", "")
                    .replace(" ", "")
                )

            os.makedirs(output_dir, exist_ok=True)
            csv_path = os.path.join(output_dir, csv_name)
            df_out.to_csv(csv_path, index=False)
            logger.info(f"因子 {factor_id} 结果已导出到 CSV: {csv_path}")

            # 回写 factor_value_files（batch_csv / daily_csv）
            try:
                rel_path = Path(csv_path).resolve().relative_to(project_root).as_posix()
            except ValueError:
                rel_path = Path(csv_path).as_posix()

            try:
                if daily_csv_mode:
                    _upsert_factor_value_files_daily_csv(
                        session,
                        factor_id=factor_id,
                        universe=universe,
                        rel_path_posix=rel_path,
                        trade_date=publish_iso,
                    )
                else:
                    _upsert_factor_value_file(
                        session,
                        factor_id=factor_id,
                        factor_name=factor_name,
                        universe=universe,
                        rel_path=rel_path,
                        date_start=publish_start_date,
                        date_end=end_date,
                        batch_id=batch_id,
                        stage=stage,
                        is_rebase=is_rebase,
                    )
                # 每个因子独立提交，提升可观测性与容错性：
                # - 中途可在 DB 看到已完成因子
                # - 单因子失败不会回滚此前成功写入
                session.commit()
            except Exception as e:
                # 不中断主计算；记录错误供后续补写。
                logger.error(
                    f"写入 factor_value_files 失败，factor_id={factor_id}, "
                    f"universe={universe}, path={rel_path}, err={e}"
                )
                # 避免 session 落入 aborted 状态影响后续因子；这里显式回滚到干净状态。
                session.rollback()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


def main():
    parser = argparse.ArgumentParser(description="因子批量计算入口（通用计算，不含增量编排）")
    parser.add_argument(
        "--config",
        default="config.ini",
        help="配置文件路径（非 prod 自动切换 _dev.ini）",
    )
    parser.add_argument("--start-date", default=None, help="覆盖配置中的 start_date")
    parser.add_argument("--end-date", default=None, help="覆盖配置中的 end_date")
    parser.add_argument("--batch-id", default=None, help="覆盖配置中的 batch_id")
    parser.add_argument(
        "--stage",
        default=None,
        choices=["candidate", "production", "deprecated"],
        help="覆盖配置中的 stage",
    )
    parser.add_argument(
        "--is-rebase",
        action="store_true",
        help="覆盖配置并标记本批次为 rebase",
    )
    parser.add_argument(
        "--no-rebase",
        action="store_true",
        help="覆盖配置并标记本批次非 rebase",
    )
    parser.add_argument(
        "--factor-ids",
        default=None,
        help="显式覆写 [factor_engine].factor_ids，逗号分隔，与 run_factor_engine(factor_ids_override=...) 一致；不传则读配置",
    )
    parser.add_argument(
        "--universe",
        default=None,
        help="显式覆写 [factor_engine].universe（如 ALL/HS300），与 run_factor_engine(universe_override=...) 一致；不传则读配置",
    )
    parser.add_argument(
        "--skip-if-batch-csv-record-exists",
        action="store_true",
        help="明确开启（默认即已开启）：已存在 batch_csv 索引则跳过；与 --no-skip-if-batch-csv-record-exists 勿同用",
    )
    parser.add_argument(
        "--no-skip-if-batch-csv-record-exists",
        action="store_true",
        help="覆盖为关闭：照常计算并写库（即使 factor_value_files 已有该键索引）",
    )
    parser.add_argument(
        "--daily-csv",
        action="store_true",
        help=(
            "日更模式：CSV 写入 factor_values/daily/by_universe/<universe>/<YYYY-MM-DD>/<factor>.csv；"
            "factor_value_files.artifact_type=daily_csv（与 factor_export 中 daily_override_batch 对齐）。"
            "发布日为 --end-date；--start-date 可更早用于 Warmup。"
        ),
    )
    args = parser.parse_args()

    is_rebase_override: Optional[bool] = None
    if args.skip_if_batch_csv_record_exists and args.no_skip_if_batch_csv_record_exists:
        raise SystemExit(
            "错误：--skip-if-batch-csv-record-exists 与 --no-skip-if-batch-csv-record-exists 不能同时使用"
        )

    if args.is_rebase and args.no_rebase:
        raise ValueError("--is-rebase 与 --no-rebase 不能同时使用")
    if args.is_rebase:
        is_rebase_override = True
    elif args.no_rebase:
        is_rebase_override = False

    factor_ids_arg: Optional[List[str]] = None
    if args.factor_ids is not None:
        factor_ids_arg = [x.strip() for x in args.factor_ids.split(",") if x.strip()]
        if not factor_ids_arg:
            raise SystemExit("错误：--factor-ids 去空白后为空，请至少给出一个 factor_id，或不要传此参数以使用配置文件")

    universe_arg: Optional[str] = None
    if args.universe is not None:
        s = str(args.universe).strip()
        if not s:
            raise SystemExit("错误：--universe 不能为全空白，或不要传此参数以使用配置文件")
        universe_arg = s

    if args.skip_if_batch_csv_record_exists:
        skip_csv_record_override_flag: Optional[bool] = True
    elif args.no_skip_if_batch_csv_record_exists:
        skip_csv_record_override_flag = False
    else:
        skip_csv_record_override_flag = None

    publish_start_cli: Optional[str] = args.end_date if args.daily_csv else args.start_date

    run_factor_engine(
        config_file=args.config,
        start_date_override=args.start_date,
        end_date_override=args.end_date,
        publish_start_date_override=publish_start_cli,
        batch_id_override=args.batch_id,
        stage_override=args.stage,
        is_rebase_override=is_rebase_override,
        factor_ids_override=factor_ids_arg,
        universe_override=universe_arg,
        skip_if_batch_csv_record_exists_override=skip_csv_record_override_flag,
        daily_csv_mode=bool(args.daily_csv),
    )


if __name__ == "__main__":
    main()

